### ISSUE TITLE
My blogs is not in the list

### ISSUE THREAD

**Issue by kasuken** [matthiasjost/dotnet-creators-opml#2]
Hi Matthias,
thank you for this great initiative!

I don't find my blog in the opml file.
Maybe because my blog is hosted on dev.to.
If you want you can change the original list in the other repo with the link: https://dev.to/kasuken and my rss feed is located: https://dev.to/feed/kasuken

**Comment by matthiasjost** [comment]
Thank you, Emanuele. I will check it!

**Comment by matthiasjost** [comment]
It says:

So Pretty clear that they do not want to have Bots.

`{StatusCode: 403, ReasonPhrase: 'Forbidden Bots', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Connection: close
  Server: Varnish
  Retry-After: 0
  Accept-Ranges: bytes
  Date: Sun, 27 Nov 2022 12:08:03 GMT
  Via: 1.1 varnish
  X-Served-By: cache-fra-eddf8230083-FRA
  X-Cache: MISS
  X-Cache-Hits: 0
  Strict-Transport-Security: max-age=31557600
  Content-Length: 0
}}`


I might just add something called "[Feed]" to the dotnet-content-creator list and just get the URL from there.

I have also been thinking about using something like a web scraping service that doesn't get black. But I do not have it as of now.

**Comment by matthiasjost** [comment]
It's now in the list via the manually added label "Blog RSS" and directly giving the URL of it.
